import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "scripts"))

from push_strategy import (
    extract_strategy_section,
    extract_staff_input_section,
    extract_tldr_section,
    _build_description_stub,
    _find_strategy_attachment,
    STRATEGY_HEADING,
    STAFF_INPUT_HEADING,
    ATTACHMENT_NOTICE,
    ATTACHMENT_NOTICE_NO_TLDR,
    STRATEGY_ATTACHMENT_TEMPLATE,
)


class TestExtractStrategySection:

    def test_extracts_strategy_section(self):
        content = (
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "This is the strategy content.\n\n"
            "### Sub-section\n\n"
            "More details here.\n"
        )
        result = extract_strategy_section(content)
        assert result is not None
        assert "## Strategy (AI Generated by Agentic SDLC Pipeline)" in result
        assert "This is the strategy content." in result
        assert "More details here." in result

    def test_returns_none_when_no_strategy_section(self):
        content = (
            "## Business Need\n\n"
            "We need this feature.\n\n"
            "## Scope\n\n"
            "It is small.\n"
        )
        result = extract_strategy_section(content)
        assert result is None

    def test_stops_at_next_h2_heading(self):
        content = (
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "Strategy content.\n\n"
            "## Staff Engineer Input\n\n"
            "Engineer notes.\n"
        )
        result = extract_strategy_section(content)
        assert result is not None
        assert "Strategy content." in result
        assert "Staff Engineer Input" not in result
        assert "Engineer notes." not in result

    def test_includes_h3_subsections(self):
        content = (
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "Overview.\n\n"
            "### Implementation Details\n\n"
            "Details here.\n\n"
            "### Testing Plan\n\n"
            "Test plan here.\n"
        )
        result = extract_strategy_section(content)
        assert result is not None
        assert "### Implementation Details" in result
        assert "### Testing Plan" in result
        assert "Details here." in result
        assert "Test plan here." in result

    def test_extraction_in_full_document(self):
        content = (
            "## Business Need\n\n"
            "Users need GPU sharing for cost efficiency.\n\n"
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "Enable time-sliced GPU sharing via MIG.\n\n"
            "### Architecture\n\n"
            "Use the NVIDIA device plugin.\n\n"
            "## Staff Engineer Input\n\n"
            "<!-- Add technical corrections here. -->\n"
        )
        result = extract_strategy_section(content)
        assert result is not None
        assert "Enable time-sliced GPU sharing via MIG." in result
        assert "Use the NVIDIA device plugin." in result
        assert "Business Need" not in result
        assert "Users need GPU sharing" not in result
        assert "Staff Engineer Input" not in result

    def test_strategy_at_end_of_file(self):
        content = (
            "## Business Need\n\n"
            "Context.\n\n"
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "Final section content.\n"
        )
        result = extract_strategy_section(content)
        assert result is not None
        assert "Final section content." in result

    def test_strategy_with_frontmatter_stripped(self):
        content = (
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "Content after frontmatter was stripped.\n"
        )
        result = extract_strategy_section(content)
        assert result is not None
        assert "Content after frontmatter was stripped." in result

    def test_wrong_heading_not_matched(self):
        content = (
            "## Strategy\n\n"
            "This heading is missing the parenthetical.\n"
        )
        result = extract_strategy_section(content)
        assert result is None

    def test_result_is_stripped(self):
        content = (
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "Content.\n\n\n"
        )
        result = extract_strategy_section(content)
        assert result is not None
        assert not result.endswith("\n\n")


class TestExtractStaffInputSection:

    def test_extracts_staff_input(self):
        content = (
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "Strategy content.\n\n"
            "## Staff Engineer Input\n\n"
            "Effort estimate is too low.\n"
        )
        result = extract_staff_input_section(content)
        assert result is not None
        assert "## Staff Engineer Input" in result
        assert "Effort estimate is too low." in result
        assert "Strategy content." not in result

    def test_returns_none_when_no_staff_input(self):
        content = (
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "Strategy content.\n"
        )
        result = extract_staff_input_section(content)
        assert result is None

    def test_extracts_template_only(self):
        content = (
            "## Staff Engineer Input\n\n"
            "<!-- Add technical corrections here. -->\n"
        )
        result = extract_staff_input_section(content)
        assert result is not None
        assert "## Staff Engineer Input" in result

    def test_staff_input_at_end_of_file(self):
        content = (
            "## Business Need\n\nContext.\n\n"
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "Strategy.\n\n"
            "## Staff Engineer Input\n\n"
            "Add dependency on RHAISTRAT-1200.\n"
        )
        result = extract_staff_input_section(content)
        assert result is not None
        assert "Add dependency on RHAISTRAT-1200." in result
        assert "Business Need" not in result
        assert "Strategy." not in result

    def test_stops_at_next_h2(self):
        content = (
            "## Staff Engineer Input\n\n"
            "Notes here.\n\n"
            "## Another Section\n\n"
            "Other content.\n"
        )
        result = extract_staff_input_section(content)
        assert result is not None
        assert "Notes here." in result
        assert "Another Section" not in result
        assert "Other content." not in result

    def test_includes_h3_subsections(self):
        content = (
            "## Staff Engineer Input\n\n"
            "Overview.\n\n"
            "### Corrections\n\n"
            "Fix the estimate.\n\n"
            "### Links\n\n"
            "See RHAISTRAT-1200.\n"
        )
        result = extract_staff_input_section(content)
        assert result is not None
        assert "### Corrections" in result
        assert "### Links" in result

    def test_result_is_stripped(self):
        content = (
            "## Staff Engineer Input\n\n"
            "Content.\n\n\n"
        )
        result = extract_staff_input_section(content)
        assert result is not None
        assert not result.endswith("\n\n")


class TestExtractTldrSection:

    def test_extracts_tldr_with_components(self):
        strategy = (
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "### TL;DR\n\n"
            "Enable GPU sharing via MIG profiles.\n\n"
            "**Components**: nvidia-device-plugin, dashboard\n\n"
            "### Technical Approach\n\n"
            "Use the NVIDIA device plugin.\n"
        )
        result = extract_tldr_section(strategy)
        assert result is not None
        assert "### TL;DR" in result
        assert "GPU sharing via MIG profiles" in result
        assert "**Components**" in result
        assert "Technical Approach" not in result

    def test_returns_none_when_no_tldr(self):
        strategy = (
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "### Technical Approach\n\n"
            "Details here.\n"
        )
        result = extract_tldr_section(strategy)
        assert result is None

    def test_tldr_at_end_of_strategy(self):
        strategy = (
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "### Technical Approach\n\nDetails.\n\n"
            "### TL;DR\n\n"
            "Final summary.\n"
        )
        result = extract_tldr_section(strategy)
        assert result is not None
        assert "Final summary." in result

    def test_tldr_stops_at_next_h3(self):
        strategy = (
            "### TL;DR\n\n"
            "Summary text.\n\n"
            "### Risks\n\n"
            "Risk details.\n"
        )
        result = extract_tldr_section(strategy)
        assert result is not None
        assert "Summary text." in result
        assert "Risks" not in result
        assert "Risk details." not in result

    def test_result_is_stripped(self):
        strategy = (
            "### TL;DR\n\n"
            "Summary.\n\n\n"
        )
        result = extract_tldr_section(strategy)
        assert result is not None
        assert not result.endswith("\n\n")


class TestBuildDescriptionStub:

    def test_stub_with_tldr(self):
        existing_md = (
            "## Business Need\n\n"
            "Users need GPU sharing.\n\n"
            f"{STRATEGY_HEADING}\n\n"
            "### TL;DR\n\n"
            "Enable GPU sharing.\n\n"
            "### Technical Approach\n\n"
            "Use MIG.\n"
        )
        strategy_section = (
            f"{STRATEGY_HEADING}\n\n"
            "### TL;DR\n\n"
            "Enable GPU sharing.\n\n"
            "### Technical Approach\n\n"
            "Use MIG.\n"
        )
        result = _build_description_stub(
            existing_md, strategy_section, None, "RHAISTRAT-1000-strategy.md")
        assert "Business Need" in result
        assert "Users need GPU sharing" in result
        assert STRATEGY_HEADING in result
        assert "### TL;DR" in result
        assert "Enable GPU sharing" in result
        assert "### Technical Approach" not in result
        assert "RHAISTRAT-1000-strategy.md" in result

    def test_stub_without_tldr(self):
        existing_md = "## Business Need\n\nContext.\n"
        strategy_section = (
            f"{STRATEGY_HEADING}\n\n"
            "### Technical Approach\n\n"
            "Details.\n"
        )
        result = _build_description_stub(
            existing_md, strategy_section, None, "RHAISTRAT-1000-strategy.md")
        assert STRATEGY_HEADING in result
        assert "### TL;DR" not in result
        assert "RHAISTRAT-1000-strategy.md" in result

    def test_stub_preserves_business_need(self):
        existing_md = (
            "## Business Need\n\n"
            "Critical business context that must be preserved.\n\n"
            f"{STRATEGY_HEADING}\n\n"
            "Old strategy.\n"
        )
        strategy_section = f"{STRATEGY_HEADING}\n\nNew strategy.\n"
        result = _build_description_stub(
            existing_md, strategy_section, None, "RHAISTRAT-1000-strategy.md")
        assert "Critical business context that must be preserved" in result

    def test_stub_includes_staff_input(self):
        existing_md = "## Business Need\n\nContext.\n"
        strategy_section = f"{STRATEGY_HEADING}\n\nStrategy.\n"
        staff_input = f"{STAFF_INPUT_HEADING}\n\nEngineer notes.\n"
        result = _build_description_stub(
            existing_md, strategy_section, staff_input,
            "RHAISTRAT-1000-strategy.md")
        assert STAFF_INPUT_HEADING in result
        assert "Engineer notes." in result

    def test_stub_adds_staff_input_template_when_missing(self):
        existing_md = "## Business Need\n\nContext.\n"
        strategy_section = f"{STRATEGY_HEADING}\n\nStrategy.\n"
        result = _build_description_stub(
            existing_md, strategy_section, None, "RHAISTRAT-1000-strategy.md")
        assert STAFF_INPUT_HEADING in result

    def test_stub_does_not_duplicate_staff_input(self):
        existing_md = (
            "## Business Need\n\nContext.\n\n"
            f"{STAFF_INPUT_HEADING}\n\nExisting notes.\n"
        )
        strategy_section = f"{STRATEGY_HEADING}\n\nStrategy.\n"
        staff_input = f"{STAFF_INPUT_HEADING}\n\nUpdated notes.\n"
        result = _build_description_stub(
            existing_md, strategy_section, staff_input,
            "RHAISTRAT-1000-strategy.md")
        count = result.count("Staff Engineer Input")
        assert count == 1


class TestFindStrategyAttachment:

    def test_finds_matching_attachment(self):
        attachments = [
            {"filename": "RHAISTRAT-1000-review.md", "id": "100"},
            {"filename": "RHAISTRAT-1000-strategy.md", "id": "200"},
        ]
        result = _find_strategy_attachment(attachments, "RHAISTRAT-1000")
        assert result is not None
        assert result["id"] == "200"

    def test_returns_none_when_no_match(self):
        attachments = [
            {"filename": "RHAISTRAT-1000-review.md", "id": "100"},
        ]
        result = _find_strategy_attachment(attachments, "RHAISTRAT-1000")
        assert result is None

    def test_returns_none_for_empty_list(self):
        result = _find_strategy_attachment([], "RHAISTRAT-1000")
        assert result is None

    def test_matches_correct_issue_key(self):
        attachments = [
            {"filename": "RHAISTRAT-2000-strategy.md", "id": "300"},
        ]
        result = _find_strategy_attachment(attachments, "RHAISTRAT-1000")
        assert result is None
