import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "scripts"))

from push_strategy import extract_strategy_section, extract_staff_input_section


class TestExtractStrategySection:

    def test_extracts_strategy_section(self):
        content = (
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "This is the strategy content.\n\n"
            "### Sub-section\n\n"
            "More details here.\n"
        )
        result = extract_strategy_section(content)
        assert result is not None
        assert "## Strategy (AI Generated by Agentic SDLC Pipeline)" in result
        assert "This is the strategy content." in result
        assert "More details here." in result

    def test_returns_none_when_no_strategy_section(self):
        content = (
            "## Business Need\n\n"
            "We need this feature.\n\n"
            "## Scope\n\n"
            "It is small.\n"
        )
        result = extract_strategy_section(content)
        assert result is None

    def test_stops_at_next_h2_heading(self):
        content = (
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "Strategy content.\n\n"
            "## Staff Engineer Input\n\n"
            "Engineer notes.\n"
        )
        result = extract_strategy_section(content)
        assert result is not None
        assert "Strategy content." in result
        assert "Staff Engineer Input" not in result
        assert "Engineer notes." not in result

    def test_includes_h3_subsections(self):
        content = (
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "Overview.\n\n"
            "### Implementation Details\n\n"
            "Details here.\n\n"
            "### Testing Plan\n\n"
            "Test plan here.\n"
        )
        result = extract_strategy_section(content)
        assert result is not None
        assert "### Implementation Details" in result
        assert "### Testing Plan" in result
        assert "Details here." in result
        assert "Test plan here." in result

    def test_extraction_in_full_document(self):
        content = (
            "## Business Need\n\n"
            "Users need GPU sharing for cost efficiency.\n\n"
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "Enable time-sliced GPU sharing via MIG.\n\n"
            "### Architecture\n\n"
            "Use the NVIDIA device plugin.\n\n"
            "## Staff Engineer Input\n\n"
            "<!-- Add technical corrections here. -->\n"
        )
        result = extract_strategy_section(content)
        assert result is not None
        assert "Enable time-sliced GPU sharing via MIG." in result
        assert "Use the NVIDIA device plugin." in result
        assert "Business Need" not in result
        assert "Users need GPU sharing" not in result
        assert "Staff Engineer Input" not in result

    def test_strategy_at_end_of_file(self):
        content = (
            "## Business Need\n\n"
            "Context.\n\n"
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "Final section content.\n"
        )
        result = extract_strategy_section(content)
        assert result is not None
        assert "Final section content." in result

    def test_strategy_with_frontmatter_stripped(self):
        content = (
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "Content after frontmatter was stripped.\n"
        )
        result = extract_strategy_section(content)
        assert result is not None
        assert "Content after frontmatter was stripped." in result

    def test_wrong_heading_not_matched(self):
        content = (
            "## Strategy\n\n"
            "This heading is missing the parenthetical.\n"
        )
        result = extract_strategy_section(content)
        assert result is None

    def test_result_is_stripped(self):
        content = (
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "Content.\n\n\n"
        )
        result = extract_strategy_section(content)
        assert result is not None
        assert not result.endswith("\n\n")


class TestExtractStaffInputSection:

    def test_extracts_staff_input(self):
        content = (
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "Strategy content.\n\n"
            "## Staff Engineer Input\n\n"
            "Effort estimate is too low.\n"
        )
        result = extract_staff_input_section(content)
        assert result is not None
        assert "## Staff Engineer Input" in result
        assert "Effort estimate is too low." in result
        assert "Strategy content." not in result

    def test_returns_none_when_no_staff_input(self):
        content = (
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "Strategy content.\n"
        )
        result = extract_staff_input_section(content)
        assert result is None

    def test_extracts_template_only(self):
        content = (
            "## Staff Engineer Input\n\n"
            "<!-- Add technical corrections here. -->\n"
        )
        result = extract_staff_input_section(content)
        assert result is not None
        assert "## Staff Engineer Input" in result

    def test_staff_input_at_end_of_file(self):
        content = (
            "## Business Need\n\nContext.\n\n"
            "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
            "Strategy.\n\n"
            "## Staff Engineer Input\n\n"
            "Add dependency on RHAISTRAT-1200.\n"
        )
        result = extract_staff_input_section(content)
        assert result is not None
        assert "Add dependency on RHAISTRAT-1200." in result
        assert "Business Need" not in result
        assert "Strategy." not in result

    def test_stops_at_next_h2(self):
        content = (
            "## Staff Engineer Input\n\n"
            "Notes here.\n\n"
            "## Another Section\n\n"
            "Other content.\n"
        )
        result = extract_staff_input_section(content)
        assert result is not None
        assert "Notes here." in result
        assert "Another Section" not in result
        assert "Other content." not in result

    def test_includes_h3_subsections(self):
        content = (
            "## Staff Engineer Input\n\n"
            "Overview.\n\n"
            "### Corrections\n\n"
            "Fix the estimate.\n\n"
            "### Links\n\n"
            "See RHAISTRAT-1200.\n"
        )
        result = extract_staff_input_section(content)
        assert result is not None
        assert "### Corrections" in result
        assert "### Links" in result

    def test_result_is_stripped(self):
        content = (
            "## Staff Engineer Input\n\n"
            "Content.\n\n\n"
        )
        result = extract_staff_input_section(content)
        assert result is not None
        assert not result.endswith("\n\n")
