"""Integration tests for push_strategy.py against jira-emulator."""
import os
import subprocess
import sys

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "scripts"))

from jira_utils import adf_to_markdown

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SCRIPT = os.path.join(PROJECT_ROOT, "scripts", "push_strategy.py")

STRATEGY_HEADING = "## Strategy (AI Generated by Agentic SDLC Pipeline)"
STAFF_INPUT_HEADING = "## Staff Engineer Input"


def _env(jira):
    return {
        **os.environ,
        "JIRA_SERVER": jira.url,
        "JIRA_USER": "admin",
        "JIRA_TOKEN": "admin",
    }


def _run(jira, issue_key, local_file):
    return subprocess.run(
        [sys.executable, SCRIPT, issue_key, str(local_file)],
        env=_env(jira),
        capture_output=True,
        text=True,
        cwd=PROJECT_ROOT,
    )


def _get_description_markdown(jira, key):
    issue = jira.get(key)
    desc = issue.get("fields", {}).get("description")
    if desc is None:
        return ""
    return adf_to_markdown(desc).strip()


class TestPushNewStrategy:

    def test_pushes_strategy_section_to_empty_description(self, jira, art_dir):
        jira.create("RHAISTRAT-1000", "Test strategy push", "")

        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1000.md"
        local_file.write_text(
            f"{STRATEGY_HEADING}\n\n"
            "### Goal\n\n"
            "Enable GPU time-slicing via MIG profiles.\n\n"
            "### Implementation\n\n"
            "Use the NVIDIA device plugin.\n"
        )

        result = _run(jira, "RHAISTRAT-1000", local_file)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        md = _get_description_markdown(jira, "RHAISTRAT-1000")
        assert "GPU time-slicing via MIG profiles" in md
        assert "NVIDIA device plugin" in md
        assert STAFF_INPUT_HEADING in md

    def test_preserves_business_need_content(self, jira, art_dir):
        jira.create("RHAISTRAT-1002", "Preserve business need",
                     "## Business Need\n\nUsers need cost-efficient GPU sharing.")

        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1002.md"
        local_file.write_text(
            f"{STRATEGY_HEADING}\n\n"
            "### Approach\n\n"
            "Time-sliced GPU sharing with MIG.\n"
        )

        result = _run(jira, "RHAISTRAT-1002", local_file)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        md = _get_description_markdown(jira, "RHAISTRAT-1002")
        assert "Business Need" in md
        assert "cost-efficient GPU sharing" in md
        assert "Time-sliced GPU sharing with MIG" in md
        assert STAFF_INPUT_HEADING in md

    def test_creates_backup_file(self, jira, art_dir):
        jira.create("RHAISTRAT-1003", "Backup test",
                     "## Business Need\n\nOriginal content for backup.")

        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1003.md"
        local_file.write_text(
            f"{STRATEGY_HEADING}\n\n"
            "Strategy content.\n"
        )

        result = _run(jira, "RHAISTRAT-1003", local_file)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        backup_path = art_dir / "artifacts" / "strat-originals" / "RHAISTRAT-1003-pre-push.md"
        assert backup_path.exists()
        backup_content = backup_path.read_text()
        assert "Original content for backup" in backup_content

    def test_appends_staff_engineer_input_template(self, jira, art_dir):
        jira.create("RHAISTRAT-1004", "Staff input template",
                     "## Business Need\n\nContext.")

        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1004.md"
        local_file.write_text(
            f"{STRATEGY_HEADING}\n\n"
            "Strategy details.\n"
        )

        result = _run(jira, "RHAISTRAT-1004", local_file)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        md = _get_description_markdown(jira, "RHAISTRAT-1004")
        assert STAFF_INPUT_HEADING in md


class TestPushReplacement:

    def test_replaces_existing_strategy_section(self, jira, art_dir):
        existing_desc = (
            "## Business Need\n\n"
            "Users need GPU sharing.\n\n"
            f"{STRATEGY_HEADING}\n\n"
            "Old strategy content that should be replaced.\n\n"
            f"{STAFF_INPUT_HEADING}\n\n"
            "Engineer notes.\n"
        )
        jira.create("RHAISTRAT-1001", "Replace strategy", existing_desc)

        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1001.md"
        local_file.write_text(
            f"{STRATEGY_HEADING}\n\n"
            "### Updated Approach\n\n"
            "Brand new strategy content.\n"
        )

        result = _run(jira, "RHAISTRAT-1001", local_file)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        md = _get_description_markdown(jira, "RHAISTRAT-1001")
        assert "Brand new strategy content" in md
        assert "Old strategy content that should be replaced" not in md

    def test_preserves_surrounding_sections(self, jira, art_dir):
        existing_desc = (
            "## Business Need\n\n"
            "Critical business context.\n\n"
            f"{STRATEGY_HEADING}\n\n"
            "Old strategy.\n\n"
            f"{STAFF_INPUT_HEADING}\n\n"
            "Staff notes.\n"
        )
        jira.create("RHAISTRAT-1005", "Preserve surroundings", existing_desc)

        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1005.md"
        local_file.write_text(
            f"{STRATEGY_HEADING}\n\n"
            "Replacement strategy.\n"
        )

        result = _run(jira, "RHAISTRAT-1005", local_file)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        md = _get_description_markdown(jira, "RHAISTRAT-1005")
        assert "Critical business context" in md
        assert "Replacement strategy" in md
        assert "Old strategy" not in md

    def test_does_not_duplicate_strategy_section(self, jira, art_dir):
        existing_desc = (
            f"{STRATEGY_HEADING}\n\n"
            "First version.\n"
        )
        jira.create("RHAISTRAT-1006", "No duplication", existing_desc)

        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1006.md"
        local_file.write_text(
            f"{STRATEGY_HEADING}\n\n"
            "Second version.\n"
        )

        result = _run(jira, "RHAISTRAT-1006", local_file)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        md = _get_description_markdown(jira, "RHAISTRAT-1006")
        count = md.count("Strategy (AI Generated by Agentic SDLC Pipeline)")
        assert count == 1
        assert "Second version" in md
        assert "First version" not in md

    def test_does_not_duplicate_staff_input(self, jira, art_dir):
        existing_desc = (
            "## Business Need\n\nContext.\n\n"
            f"{STRATEGY_HEADING}\n\nOld strat.\n\n"
            f"{STAFF_INPUT_HEADING}\n\nExisting engineer notes.\n"
        )
        jira.create("RHAISTRAT-1007", "No duplicate staff input", existing_desc)

        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1007.md"
        local_file.write_text(
            f"{STRATEGY_HEADING}\n\n"
            "New strat.\n"
        )

        result = _run(jira, "RHAISTRAT-1007", local_file)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        md = _get_description_markdown(jira, "RHAISTRAT-1007")
        count = md.count("Staff Engineer Input")
        assert count == 1


class TestPushErrors:

    def test_missing_strategy_section_exits_1(self, jira, art_dir):
        jira.create("RHAISTRAT-1010", "No strategy", "Business need only.")

        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1010.md"
        local_file.write_text(
            "## Business Need\n\n"
            "This file has no strategy section.\n"
        )

        result = _run(jira, "RHAISTRAT-1010", local_file)
        assert result.returncode == 1
        assert "no strategy section" in result.stderr.lower()

    def test_missing_env_vars_exits_2(self, jira, art_dir):
        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1011.md"
        local_file.write_text(
            f"{STRATEGY_HEADING}\n\nContent.\n"
        )

        env = {k: v for k, v in os.environ.items()
               if k not in ("JIRA_SERVER", "JIRA_USER", "JIRA_TOKEN")}
        result = subprocess.run(
            [sys.executable, SCRIPT, "RHAISTRAT-1011", str(local_file)],
            env=env,
            capture_output=True,
            text=True,
            cwd=PROJECT_ROOT,
        )
        assert result.returncode == 2

    def test_missing_local_file_exits_nonzero(self, jira, art_dir):
        nonexistent = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1012.md"

        result = _run(jira, "RHAISTRAT-1012", nonexistent)
        assert result.returncode != 0


class TestPushBackupBehavior:

    def test_backup_not_overwritten_on_second_push(self, jira, art_dir):
        jira.create("RHAISTRAT-1020", "Backup idempotency",
                     "## Business Need\n\nOriginal content.")

        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1020.md"

        local_file.write_text(
            f"{STRATEGY_HEADING}\n\nFirst push.\n"
        )
        result1 = _run(jira, "RHAISTRAT-1020", local_file)
        assert result1.returncode == 0, f"stderr: {result1.stderr}"

        backup_path = art_dir / "artifacts" / "strat-originals" / "RHAISTRAT-1020-pre-push.md"
        assert backup_path.exists()
        first_backup = backup_path.read_text()
        assert "Original content" in first_backup

        local_file.write_text(
            f"{STRATEGY_HEADING}\n\nSecond push.\n"
        )
        result2 = _run(jira, "RHAISTRAT-1020", local_file)
        assert result2.returncode == 0, f"stderr: {result2.stderr}"

        second_backup = backup_path.read_text()
        assert second_backup == first_backup

    def test_no_backup_when_description_empty(self, jira, art_dir):
        jira.create("RHAISTRAT-1021", "Empty desc", "")

        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1021.md"
        local_file.write_text(
            f"{STRATEGY_HEADING}\n\nContent.\n"
        )

        result = _run(jira, "RHAISTRAT-1021", local_file)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        backup_path = art_dir / "artifacts" / "strat-originals" / "RHAISTRAT-1021-pre-push.md"
        assert not backup_path.exists()


class TestPushWithFrontmatter:

    def test_frontmatter_is_stripped_before_push(self, jira, art_dir):
        jira.create("RHAISTRAT-1030", "Frontmatter stripping", "")

        local_file = art_dir / "artifacts" / "strat-tasks" / "RHAISTRAT-1030.md"
        local_file.write_text(
            "---\n"
            "status: refined\n"
            "source_rfe: RHAIRFE-1030\n"
            "---\n\n"
            "# RHAISTRAT-1030: Test Title\n\n"
            f"{STRATEGY_HEADING}\n\n"
            "Strategy content after frontmatter.\n"
        )

        result = _run(jira, "RHAISTRAT-1030", local_file)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        md = _get_description_markdown(jira, "RHAISTRAT-1030")
        assert "status: refined" not in md
        assert "source_rfe:" not in md
        assert "RHAISTRAT-1030: Test Title" not in md
        assert "Strategy content after frontmatter" in md
