"""Integration tests for pull_strategy.py against jira-emulator."""
import json
import os
import subprocess
import sys

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "scripts"))

from artifact_utils import read_frontmatter
from jira_utils import markdown_to_adf

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
SCRIPT = os.path.join(PROJECT_ROOT, "scripts", "pull_strategy.py")


def _env(jira):
    return {
        **os.environ,
        "JIRA_SERVER": jira.url,
        "JIRA_USER": "admin",
        "JIRA_TOKEN": "admin",
    }


def _run(jira, strat_key, local_dir, extra_args=None):
    cmd = [sys.executable, SCRIPT, strat_key, "--local-dir", str(local_dir)]
    if extra_args:
        cmd.extend(extra_args)
    return subprocess.run(
        cmd,
        env=_env(jira),
        capture_output=True,
        text=True,
        cwd=PROJECT_ROOT,
    )


def _setup_strat_with_rfe(jira, strat_key, rfe_key, labels=None):
    """Create a STRAT issue linked to an RFE via Cloners."""
    desc_md = (
        "## Business Need (from RFE)\n\n"
        "Users need GPU sharing.\n\n"
        "## Strategy (AI Generated by Agentic SDLC Pipeline)\n\n"
        "### Technical Approach\n\n"
        "Use MIG profiles for GPU time-slicing.\n"
    )
    jira.create(strat_key, "GPU time-slicing strategy", desc_md,
                labels=labels or [])
    jira.create(rfe_key, "GPU sharing RFE",
                "Users need cost-efficient GPU sharing.")

    jira.request("POST", "/rest/api/3/issueLink", {
        "type": {"name": "Cloners"},
        "inwardIssue": {"key": strat_key},
        "outwardIssue": {"key": rfe_key},
    })


class TestPullWithRubricPass:

    def test_pulls_strategy_file(self, jira, tmp_path):
        _setup_strat_with_rfe(jira, "RHAISTRAT-2000", "RHAIRFE-3000",
                              labels=["strat-creator-rubric-pass"])

        local_dir = tmp_path / "local"
        result = _run(jira, "RHAISTRAT-2000", local_dir)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        strat_path = local_dir / "strat-tasks" / "RHAISTRAT-2000.md"
        assert strat_path.exists()

        data, body = read_frontmatter(str(strat_path))
        assert data["strat_id"] == "RHAISTRAT-2000"
        assert data["workflow"] == "local"
        assert data["source_rfe"] == "RHAIRFE-3000"
        assert "GPU time-slicing" in body

    def test_pulls_rfe_original(self, jira, tmp_path):
        _setup_strat_with_rfe(jira, "RHAISTRAT-2001", "RHAIRFE-3001",
                              labels=["strat-creator-rubric-pass"])

        local_dir = tmp_path / "local"
        result = _run(jira, "RHAISTRAT-2001", local_dir)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        rfe_path = local_dir / "strat-originals" / "RHAIRFE-3001.md"
        assert rfe_path.exists()
        assert "GPU sharing" in rfe_path.read_text()

    def test_frontmatter_has_correct_fields(self, jira, tmp_path):
        _setup_strat_with_rfe(jira, "RHAISTRAT-2002", "RHAIRFE-3002",
                              labels=["strat-creator-rubric-pass"])

        local_dir = tmp_path / "local"
        _run(jira, "RHAISTRAT-2002", local_dir)

        strat_path = local_dir / "strat-tasks" / "RHAISTRAT-2002.md"
        data, _ = read_frontmatter(str(strat_path))
        assert data["strat_id"] == "RHAISTRAT-2002"
        assert data["jira_key"] == "RHAISTRAT-2002"
        assert data["source_rfe"] == "RHAIRFE-3002"
        assert data["status"] == "Refined"
        assert data["workflow"] == "local"
        assert data["title"] == "GPU time-slicing strategy"


class TestPullWithNeedsAttention:

    def test_pulls_strategy_with_needs_attention(self, jira, tmp_path):
        _setup_strat_with_rfe(jira, "RHAISTRAT-2010", "RHAIRFE-3010",
                              labels=["strat-creator-needs-attention"])

        local_dir = tmp_path / "local"
        result = _run(jira, "RHAISTRAT-2010", local_dir)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        strat_path = local_dir / "strat-tasks" / "RHAISTRAT-2010.md"
        assert strat_path.exists()
        data, _ = read_frontmatter(str(strat_path))
        assert data["workflow"] == "local"


class TestPullGateChecks:

    def test_rejects_strategy_without_post_ci_labels(self, jira, tmp_path):
        jira.create("RHAISTRAT-2020", "No labels strategy", "Some content")

        local_dir = tmp_path / "local"
        result = _run(jira, "RHAISTRAT-2020", local_dir)
        assert result.returncode == 1
        assert "post-CI label" in result.stderr

        strat_path = local_dir / "strat-tasks" / "RHAISTRAT-2020.md"
        assert not strat_path.exists()

    def test_rejects_strategy_with_wrong_labels(self, jira, tmp_path):
        jira.create("RHAISTRAT-2021", "Wrong labels", "Content",
                    labels=["strat-creator-auto-created"])

        local_dir = tmp_path / "local"
        result = _run(jira, "RHAISTRAT-2021", local_dir)
        assert result.returncode == 1

    def test_rejects_non_rhaistrat_key(self, jira, tmp_path):
        local_dir = tmp_path / "local"
        result = _run(jira, "RHAIRFE-9999", local_dir)
        assert result.returncode == 1
        assert "RHAISTRAT-NNNN" in result.stderr


class TestPullMissingCredentials:

    def test_exits_code_2_without_env_vars(self, tmp_path):
        env = {k: v for k, v in os.environ.items()
               if k not in ("JIRA_SERVER", "JIRA_USER", "JIRA_TOKEN")}
        local_dir = tmp_path / "local"
        result = subprocess.run(
            [sys.executable, SCRIPT, "RHAISTRAT-9999",
             "--local-dir", str(local_dir)],
            env=env,
            capture_output=True,
            text=True,
            cwd=PROJECT_ROOT,
        )
        assert result.returncode == 2


class TestPullReviewComment:

    def test_extracts_review_comment(self, jira, tmp_path):
        _setup_strat_with_rfe(jira, "RHAISTRAT-2030", "RHAIRFE-3030",
                              labels=["strat-creator-rubric-pass"])

        review_md = (
            "*[Strat Creator]* Strategy Review — APPROVE (Score: 7/8)\n\n"
            "| Criterion | Score |\n"
            "| --- | --- |\n"
            "| Feasibility | 2/2 |\n"
        )
        review_adf = markdown_to_adf(review_md)
        jira.request("POST", f"/rest/api/3/issue/RHAISTRAT-2030/comment",
                     {"body": review_adf})

        local_dir = tmp_path / "local"
        result = _run(jira, "RHAISTRAT-2030", local_dir)
        assert result.returncode == 0, f"stderr: {result.stderr}"

        review_path = local_dir / "strat-reviews" / "RHAISTRAT-2030-review.md"
        assert review_path.exists()
        content = review_path.read_text()
        assert "[Strat Creator]" in content
        assert "APPROVE" in content
