# EvalHub RFEs from Matteo's team
test_rfes:
  - id: RHAIRFE-1784
  - id: RHAIRFE-1783
  - id: RHAIRFE-1782
  - id: RHAIRFE-1755
  - id: RHAIRFE-1754
  - id: RHAIRFE-1753
  - id: RHAIRFE-1752
  - id: RHAIRFE-1751
  - id: RHAIRFE-1696
  - id: RHAIRFE-1695
  - id: RHAIRFE-1694
  - id: RHAIRFE-1693
  - id: RHAIRFE-1692
  - id: RHAIRFE-1691
  - id: RHAIRFE-1690
  - id: RHAIRFE-1689
  - id: RHAIRFE-1688
  - id: RHAIRFE-1676
  - id: RHAIRFE-1675
  - id: RHAIRFE-1674
  - id: RHAIRFE-1673
  - id: RHAIRFE-1672
  - id: RHAIRFE-1671
  - id: RHAIRFE-1670
  - id: RHAIRFE-1669
  - id: RHAIRFE-1668
